### PR TITLE
Modify assemblies to be variants instead of product with few minor fixes

### PR DESCRIPTION
**Pull request by nishant-cyro**
This PR allows to add parts on variant level instead of just product level.

Please refer - #132

### CODE REVIEW

**Comment by nishant-cyro** [comment]
@Mafi88 - Closed the previous PR https://github.com/spree-contrib/spree-product-assembly/pull/135 and created this one.

Specs in this one are failing due to an issue in spree_cmd. Raised a PR to fix it on spree - https://github.com/spree-contrib/spree-product-assembly/pull/135

**Comment by nishant-cyro** [comment]
@Mafi88 @vinniefranco - The specs have been fixed now with all the changes specified in https://github.com/spree-contrib/spree-product-assembly/pull/135.

Please let me know if this PR seems fine to you or there is still something remaining that needs to be fixed. :)

**Comment by Mafi88** [comment]
@nishant-cyro :+1:

**Comment by damianlegawiec** [comment]
@nishant-cyro will be QA-ing this today

**Comment by nishant-cyro** [comment]
Thanks @damianlegawiec, please let me know if there is anything I have missed or can be improved :)

**Pull request merged**
