### PR TITLE
Add parts in variants

### PR DESCRIPTION
**Pull request by stevenbarragan**
* Move all parts logic to variant
* Fix all failing test
* Display variant's parts in product show view
* Allow to add parts to variants in backend
* And refactor some messy stuff

An assembly product could include product's parts plus variant's parts, or only product's parts.

### CODE REVIEW

**Comment by proletarian** [comment]
Will this get merged?

**Comment by huoxito** [comment]
@proletarian probably not, the project hasn't been maintained and I think it needs a working 2-4-stable before we put in new features

**Comment by proletarian** [comment]
Thanks @huoxito. Do you know if there is an alternative project for this purpose? If not, I'll probably need to use this for now and contribute a branch back later.

**Comment by huoxito** [comment]
nope, can't think of any other right now sorry

**Comment by tesserakt** [comment]
@stevenbarragan great work. Was this for 2.2 initially?

**Comment by stevenbarragan** [comment]
Thank you @tesserakt, yes it was for 2.2. I hope, somehow it gets merged.

**Comment by tesserakt** [comment]
@stevenbarragan awesome. Are you using it in production?

**Comment by stevenbarragan** [comment]
To be honest, I'm not sure if they are still using it, I got another job, but we used it on production in that time.

**Comment by proletarian** [comment]
Cool, I'm going to give it a whirl since we need it in production asap.
FWIW I think this should be in Core, awesome stuff @stevenbarragan

**Comment by stevenbarragan** [comment]
Sweet, I hope it works for you as well.

**Comment by vinniefranco** [comment]
Is there still any interest for this feature? It's way out of date.

**Comment by vinniefranco** [comment]
Closing as stale

**Comment by jumski** [comment]
I am super interested in rebasing it on top of `3-0-stable`. Made a first try but got stuck somewhere in the middle, on huge conflicts in specs (some whole-file indenting were being made there?).

Anyway, i could invest some time in getting it into shape, but would like to have some feedback from you guys - anyone with good understanding of the changes between 2.4 and 3.0, compared to changes in this PR? Is it even doable given 3-0-stable state?

Please ping me! Cheers

**Pull request closed without merging**
