### PR TITLE
Added Spree 2.4 support

### PR DESCRIPTION
**Pull request by smartacus**
This adds Spree 2.4 support to spree-product-assembly.

### CODE REVIEW

**Comment by anthonynavarre** [comment]
We just started looking into doing the same update for a project ourselves, and started looking at the test failure that came up on Travis around checkout_spec.rb:44 (we're getting the same failure locally).

It's confusing, because the screens leading up to the assertion all list the variant's SKU (in this case "SKU-2") but the SKU displayed on `admin_orders_path` shows up as the product's master variant ("SKU-1").

This makes me wonder if checkout_spec.rb:48 was intended to read as `page.should have_content(variant.sku)` instead of `page.should have_content(variant.product.name)` — in either case, it's hard to tell whether the test, implementation or both are wrong.

Let me know if you'd rather I just open a separate issue for this.

**Comment by dfreerksen** [comment]
Weird. I just ran the tests with the same version of Ruby (2.0.0-p598) that failed for Travis CI and all tests passed.

**Comment by huoxito** [comment]
thanks a lot @smartacus! I wanted to take a look at this myself, looking forward to take a closer look at the PR

**Comment by smartacus** [comment]
Thank you for merging this @huoxito. By the way, I believe this PR resolves the following...

Pull Requests: #103, #106 
Issues: #100, #102, #105 (and possibly #99)

**Comment by huoxito** [comment]
thanks @smartacus, closed some of those I'm not sure I understand the availability problem yet, need more time to look into it. Either way this does seem to run smooth on spree 2.4 now thanks a lot

**Pull request merged**
